// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: ledgers/bank_payment_service.proto

package ledgers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BankPaymentServiceClient is the client API for BankPaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankPaymentServiceClient interface {
	Create(ctx context.Context, in *BankPayment, opts ...grpc.CallOption) (*BankPayment, error)
	View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BankPayment, error)
	Update(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BankPayment, error)
	List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (BankPaymentService_ListClient, error)
}

type bankPaymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankPaymentServiceClient(cc grpc.ClientConnInterface) BankPaymentServiceClient {
	return &bankPaymentServiceClient{cc}
}

func (c *bankPaymentServiceClient) Create(ctx context.Context, in *BankPayment, opts ...grpc.CallOption) (*BankPayment, error) {
	out := new(BankPayment)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.BankPaymentService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankPaymentServiceClient) View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BankPayment, error) {
	out := new(BankPayment)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.BankPaymentService/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankPaymentServiceClient) Update(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BankPayment, error) {
	out := new(BankPayment)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.BankPaymentService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankPaymentServiceClient) List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (BankPaymentService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &BankPaymentService_ServiceDesc.Streams[0], "/wiradata.ledgers.BankPaymentService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &bankPaymentServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BankPaymentService_ListClient interface {
	Recv() (*BankPayment, error)
	grpc.ClientStream
}

type bankPaymentServiceListClient struct {
	grpc.ClientStream
}

func (x *bankPaymentServiceListClient) Recv() (*BankPayment, error) {
	m := new(BankPayment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BankPaymentServiceServer is the server API for BankPaymentService service.
// All implementations must embed UnimplementedBankPaymentServiceServer
// for forward compatibility
type BankPaymentServiceServer interface {
	Create(context.Context, *BankPayment) (*BankPayment, error)
	View(context.Context, *Id) (*BankPayment, error)
	Update(context.Context, *Id) (*BankPayment, error)
	List(*EmptyMessage, BankPaymentService_ListServer) error
	mustEmbedUnimplementedBankPaymentServiceServer()
}

// UnimplementedBankPaymentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBankPaymentServiceServer struct {
}

func (UnimplementedBankPaymentServiceServer) Create(context.Context, *BankPayment) (*BankPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBankPaymentServiceServer) View(context.Context, *Id) (*BankPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedBankPaymentServiceServer) Update(context.Context, *Id) (*BankPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBankPaymentServiceServer) List(*EmptyMessage, BankPaymentService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBankPaymentServiceServer) mustEmbedUnimplementedBankPaymentServiceServer() {}

// UnsafeBankPaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankPaymentServiceServer will
// result in compilation errors.
type UnsafeBankPaymentServiceServer interface {
	mustEmbedUnimplementedBankPaymentServiceServer()
}

func RegisterBankPaymentServiceServer(s grpc.ServiceRegistrar, srv BankPaymentServiceServer) {
	s.RegisterService(&BankPaymentService_ServiceDesc, srv)
}

func _BankPaymentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankPayment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankPaymentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.BankPaymentService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankPaymentServiceServer).Create(ctx, req.(*BankPayment))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankPaymentService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankPaymentServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.BankPaymentService/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankPaymentServiceServer).View(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankPaymentService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankPaymentServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.BankPaymentService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankPaymentServiceServer).Update(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankPaymentService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BankPaymentServiceServer).List(m, &bankPaymentServiceListServer{stream})
}

type BankPaymentService_ListServer interface {
	Send(*BankPayment) error
	grpc.ServerStream
}

type bankPaymentServiceListServer struct {
	grpc.ServerStream
}

func (x *bankPaymentServiceListServer) Send(m *BankPayment) error {
	return x.ServerStream.SendMsg(m)
}

// BankPaymentService_ServiceDesc is the grpc.ServiceDesc for BankPaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankPaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wiradata.ledgers.BankPaymentService",
	HandlerType: (*BankPaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BankPaymentService_Create_Handler,
		},
		{
			MethodName: "View",
			Handler:    _BankPaymentService_View_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BankPaymentService_Update_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _BankPaymentService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ledgers/bank_payment_service.proto",
}
