// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: ledgers/bank_account_service.proto

package ledgers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BankAccountServiceClient is the client API for BankAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankAccountServiceClient interface {
	Create(ctx context.Context, in *BankAccount, opts ...grpc.CallOption) (*BankAccount, error)
	View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BankAccount, error)
	Update(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BankAccount, error)
	List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (BankAccountService_ListClient, error)
}

type bankAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankAccountServiceClient(cc grpc.ClientConnInterface) BankAccountServiceClient {
	return &bankAccountServiceClient{cc}
}

func (c *bankAccountServiceClient) Create(ctx context.Context, in *BankAccount, opts ...grpc.CallOption) (*BankAccount, error) {
	out := new(BankAccount)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.BankAccountService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankAccountServiceClient) View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BankAccount, error) {
	out := new(BankAccount)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.BankAccountService/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankAccountServiceClient) Update(ctx context.Context, in *Id, opts ...grpc.CallOption) (*BankAccount, error) {
	out := new(BankAccount)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.BankAccountService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankAccountServiceClient) List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (BankAccountService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &BankAccountService_ServiceDesc.Streams[0], "/wiradata.ledgers.BankAccountService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &bankAccountServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BankAccountService_ListClient interface {
	Recv() (*BankAccount, error)
	grpc.ClientStream
}

type bankAccountServiceListClient struct {
	grpc.ClientStream
}

func (x *bankAccountServiceListClient) Recv() (*BankAccount, error) {
	m := new(BankAccount)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BankAccountServiceServer is the server API for BankAccountService service.
// All implementations must embed UnimplementedBankAccountServiceServer
// for forward compatibility
type BankAccountServiceServer interface {
	Create(context.Context, *BankAccount) (*BankAccount, error)
	View(context.Context, *Id) (*BankAccount, error)
	Update(context.Context, *Id) (*BankAccount, error)
	List(*EmptyMessage, BankAccountService_ListServer) error
	mustEmbedUnimplementedBankAccountServiceServer()
}

// UnimplementedBankAccountServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBankAccountServiceServer struct {
}

func (UnimplementedBankAccountServiceServer) Create(context.Context, *BankAccount) (*BankAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBankAccountServiceServer) View(context.Context, *Id) (*BankAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedBankAccountServiceServer) Update(context.Context, *Id) (*BankAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBankAccountServiceServer) List(*EmptyMessage, BankAccountService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBankAccountServiceServer) mustEmbedUnimplementedBankAccountServiceServer() {}

// UnsafeBankAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankAccountServiceServer will
// result in compilation errors.
type UnsafeBankAccountServiceServer interface {
	mustEmbedUnimplementedBankAccountServiceServer()
}

func RegisterBankAccountServiceServer(s grpc.ServiceRegistrar, srv BankAccountServiceServer) {
	s.RegisterService(&BankAccountService_ServiceDesc, srv)
}

func _BankAccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankAccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.BankAccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankAccountServiceServer).Create(ctx, req.(*BankAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankAccountService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankAccountServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.BankAccountService/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankAccountServiceServer).View(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankAccountService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankAccountServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.BankAccountService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankAccountServiceServer).Update(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankAccountService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BankAccountServiceServer).List(m, &bankAccountServiceListServer{stream})
}

type BankAccountService_ListServer interface {
	Send(*BankAccount) error
	grpc.ServerStream
}

type bankAccountServiceListServer struct {
	grpc.ServerStream
}

func (x *bankAccountServiceListServer) Send(m *BankAccount) error {
	return x.ServerStream.SendMsg(m)
}

// BankAccountService_ServiceDesc is the grpc.ServiceDesc for BankAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wiradata.ledgers.BankAccountService",
	HandlerType: (*BankAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BankAccountService_Create_Handler,
		},
		{
			MethodName: "View",
			Handler:    _BankAccountService_View_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BankAccountService_Update_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _BankAccountService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ledgers/bank_account_service.proto",
}
