// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.13.0
// source: ledgers/debt_message.proto

package ledgers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Debt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     string  `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	PurchaseId    string  `protobuf:"bytes,3,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	PurchaseCode  string  `protobuf:"bytes,4,opt,name=purchase_code,json=purchaseCode,proto3" json:"purchase_code,omitempty"`
	SupplierId    string  `protobuf:"bytes,5,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	SupplierName  string  `protobuf:"bytes,6,opt,name=supplier_name,json=supplierName,proto3" json:"supplier_name,omitempty"`
	DueDate       string  `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	AmountOwed    float64 `protobuf:"fixed64,8,opt,name=amount_owed,json=amountOwed,proto3" json:"amount_owed,omitempty"`
	AmountPaid    float64 `protobuf:"fixed64,9,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	PaymentStatus string  `protobuf:"bytes,10,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	Payments      []byte  `protobuf:"bytes,11,opt,name=payments,proto3" json:"payments,omitempty"`
}

func (x *Debt) Reset() {
	*x = Debt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ledgers_debt_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Debt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debt) ProtoMessage() {}

func (x *Debt) ProtoReflect() protoreflect.Message {
	mi := &file_ledgers_debt_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debt.ProtoReflect.Descriptor instead.
func (*Debt) Descriptor() ([]byte, []int) {
	return file_ledgers_debt_message_proto_rawDescGZIP(), []int{0}
}

func (x *Debt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Debt) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Debt) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *Debt) GetPurchaseCode() string {
	if x != nil {
		return x.PurchaseCode
	}
	return ""
}

func (x *Debt) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *Debt) GetSupplierName() string {
	if x != nil {
		return x.SupplierName
	}
	return ""
}

func (x *Debt) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *Debt) GetAmountOwed() float64 {
	if x != nil {
		return x.AmountOwed
	}
	return 0
}

func (x *Debt) GetAmountPaid() float64 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

func (x *Debt) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *Debt) GetPayments() []byte {
	if x != nil {
		return x.Payments
	}
	return nil
}

type Debts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Debt []*Debt `protobuf:"bytes,1,rep,name=debt,proto3" json:"debt,omitempty"`
}

func (x *Debts) Reset() {
	*x = Debts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ledgers_debt_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Debts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debts) ProtoMessage() {}

func (x *Debts) ProtoReflect() protoreflect.Message {
	mi := &file_ledgers_debt_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debts.ProtoReflect.Descriptor instead.
func (*Debts) Descriptor() ([]byte, []int) {
	return file_ledgers_debt_message_proto_rawDescGZIP(), []int{1}
}

func (x *Debts) GetDebt() []*Debt {
	if x != nil {
		return x.Debt
	}
	return nil
}

var File_ledgers_debt_message_proto protoreflect.FileDescriptor

var file_ledgers_debt_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x2f, 0x64, 0x65, 0x62, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x77, 0x69,
	0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x22, 0xe1,
	0x02, 0x0a, 0x04, 0x44, 0x65, 0x62, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x75, 0x72, 0x63, 0x68,
	0x61, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x75, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x75, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x77, 0x65, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x69, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x69, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x33, 0x0a, 0x05, 0x44, 0x65, 0x62, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x04, 0x64,
	0x65, 0x62, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x69, 0x72, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x44, 0x65, 0x62,
	0x74, 0x52, 0x04, 0x64, 0x65, 0x62, 0x74, 0x42, 0x3b, 0x0a, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x77,
	0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x65, 0x72, 0x70, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x50, 0x01,
	0x5a, 0x12, 0x70, 0x62, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x3b, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ledgers_debt_message_proto_rawDescOnce sync.Once
	file_ledgers_debt_message_proto_rawDescData = file_ledgers_debt_message_proto_rawDesc
)

func file_ledgers_debt_message_proto_rawDescGZIP() []byte {
	file_ledgers_debt_message_proto_rawDescOnce.Do(func() {
		file_ledgers_debt_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_ledgers_debt_message_proto_rawDescData)
	})
	return file_ledgers_debt_message_proto_rawDescData
}

var file_ledgers_debt_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ledgers_debt_message_proto_goTypes = []interface{}{
	(*Debt)(nil),  // 0: wiradata.ledgers.Debt
	(*Debts)(nil), // 1: wiradata.ledgers.Debts
}
var file_ledgers_debt_message_proto_depIdxs = []int32{
	0, // 0: wiradata.ledgers.Debts.debt:type_name -> wiradata.ledgers.Debt
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ledgers_debt_message_proto_init() }
func file_ledgers_debt_message_proto_init() {
	if File_ledgers_debt_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ledgers_debt_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Debt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ledgers_debt_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Debts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ledgers_debt_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ledgers_debt_message_proto_goTypes,
		DependencyIndexes: file_ledgers_debt_message_proto_depIdxs,
		MessageInfos:      file_ledgers_debt_message_proto_msgTypes,
	}.Build()
	File_ledgers_debt_message_proto = out.File
	file_ledgers_debt_message_proto_rawDesc = nil
	file_ledgers_debt_message_proto_goTypes = nil
	file_ledgers_debt_message_proto_depIdxs = nil
}
