// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.13.0
// source: ledgers/general_journal_message.proto

package ledgers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_CASH_RECEIPT TransactionType = 0
	TransactionType_CASH_PAYMENT TransactionType = 1
	TransactionType_BANK_RECEIPT TransactionType = 2
	TransactionType_BANK_PAYMENT TransactionType = 3
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "CASH_RECEIPT",
		1: "CASH_PAYMENT",
		2: "BANK_RECEIPT",
		3: "BANK_PAYMENT",
	}
	TransactionType_value = map[string]int32{
		"CASH_RECEIPT": 0,
		"CASH_PAYMENT": 1,
		"BANK_RECEIPT": 2,
		"BANK_PAYMENT": 3,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_ledgers_general_journal_message_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_ledgers_general_journal_message_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_ledgers_general_journal_message_proto_rawDescGZIP(), []int{0}
}

type GeneralJournal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId       string          `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Code            string          `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Date            string          `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Name            string          `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	TransactionType TransactionType `protobuf:"varint,6,opt,name=transaction_type,json=transactionType,proto3,enum=wiradata.ledgers.TransactionType" json:"transaction_type,omitempty"`
	Transaction     []byte          `protobuf:"bytes,7,opt,name=transaction,proto3" json:"transaction,omitempty"`
	CreatedAt       string          `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy       string          `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt       string          `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy       string          `protobuf:"bytes,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
}

func (x *GeneralJournal) Reset() {
	*x = GeneralJournal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ledgers_general_journal_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralJournal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralJournal) ProtoMessage() {}

func (x *GeneralJournal) ProtoReflect() protoreflect.Message {
	mi := &file_ledgers_general_journal_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralJournal.ProtoReflect.Descriptor instead.
func (*GeneralJournal) Descriptor() ([]byte, []int) {
	return file_ledgers_general_journal_message_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralJournal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GeneralJournal) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GeneralJournal) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GeneralJournal) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GeneralJournal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeneralJournal) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_CASH_RECEIPT
}

func (x *GeneralJournal) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *GeneralJournal) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GeneralJournal) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *GeneralJournal) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GeneralJournal) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

var File_ledgers_general_journal_message_proto protoreflect.FileDescriptor

var file_ledgers_general_journal_message_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x5f, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x22, 0xe7, 0x02, 0x0a, 0x0e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4c, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x21, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x62, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x79, 0x2a, 0x59, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x41, 0x53, 0x48, 0x5f, 0x52,
	0x45, 0x43, 0x45, 0x49, 0x50, 0x54, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x41, 0x53, 0x48,
	0x5f, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x41,
	0x4e, 0x4b, 0x5f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x50, 0x54, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c,
	0x42, 0x41, 0x4e, 0x4b, 0x5f, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x03, 0x42, 0x3b,
	0x0a, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x65,
	0x72, 0x70, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x73, 0x50, 0x01, 0x5a, 0x12, 0x70, 0x62, 0x2f, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x73, 0x3b, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ledgers_general_journal_message_proto_rawDescOnce sync.Once
	file_ledgers_general_journal_message_proto_rawDescData = file_ledgers_general_journal_message_proto_rawDesc
)

func file_ledgers_general_journal_message_proto_rawDescGZIP() []byte {
	file_ledgers_general_journal_message_proto_rawDescOnce.Do(func() {
		file_ledgers_general_journal_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_ledgers_general_journal_message_proto_rawDescData)
	})
	return file_ledgers_general_journal_message_proto_rawDescData
}

var file_ledgers_general_journal_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ledgers_general_journal_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ledgers_general_journal_message_proto_goTypes = []interface{}{
	(TransactionType)(0),   // 0: wiradata.ledgers.TransactionType
	(*GeneralJournal)(nil), // 1: wiradata.ledgers.GeneralJournal
}
var file_ledgers_general_journal_message_proto_depIdxs = []int32{
	0, // 0: wiradata.ledgers.GeneralJournal.transaction_type:type_name -> wiradata.ledgers.TransactionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ledgers_general_journal_message_proto_init() }
func file_ledgers_general_journal_message_proto_init() {
	if File_ledgers_general_journal_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ledgers_general_journal_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralJournal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ledgers_general_journal_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ledgers_general_journal_message_proto_goTypes,
		DependencyIndexes: file_ledgers_general_journal_message_proto_depIdxs,
		EnumInfos:         file_ledgers_general_journal_message_proto_enumTypes,
		MessageInfos:      file_ledgers_general_journal_message_proto_msgTypes,
	}.Build()
	File_ledgers_general_journal_message_proto = out.File
	file_ledgers_general_journal_message_proto_rawDesc = nil
	file_ledgers_general_journal_message_proto_goTypes = nil
	file_ledgers_general_journal_message_proto_depIdxs = nil
}
