// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: ledgers/general_journal_service.proto

package ledgers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GeneralJournalServiceClient is the client API for GeneralJournalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeneralJournalServiceClient interface {
	List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (GeneralJournalService_ListClient, error)
	Posting(ctx context.Context, in *Id, opts ...grpc.CallOption) (*GeneralLedger, error)
}

type generalJournalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneralJournalServiceClient(cc grpc.ClientConnInterface) GeneralJournalServiceClient {
	return &generalJournalServiceClient{cc}
}

func (c *generalJournalServiceClient) List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (GeneralJournalService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &GeneralJournalService_ServiceDesc.Streams[0], "/wiradata.ledgers.GeneralJournalService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &generalJournalServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GeneralJournalService_ListClient interface {
	Recv() (*GeneralJournal, error)
	grpc.ClientStream
}

type generalJournalServiceListClient struct {
	grpc.ClientStream
}

func (x *generalJournalServiceListClient) Recv() (*GeneralJournal, error) {
	m := new(GeneralJournal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *generalJournalServiceClient) Posting(ctx context.Context, in *Id, opts ...grpc.CallOption) (*GeneralLedger, error) {
	out := new(GeneralLedger)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.GeneralJournalService/Posting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneralJournalServiceServer is the server API for GeneralJournalService service.
// All implementations must embed UnimplementedGeneralJournalServiceServer
// for forward compatibility
type GeneralJournalServiceServer interface {
	List(*EmptyMessage, GeneralJournalService_ListServer) error
	Posting(context.Context, *Id) (*GeneralLedger, error)
	mustEmbedUnimplementedGeneralJournalServiceServer()
}

// UnimplementedGeneralJournalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGeneralJournalServiceServer struct {
}

func (UnimplementedGeneralJournalServiceServer) List(*EmptyMessage, GeneralJournalService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedGeneralJournalServiceServer) Posting(context.Context, *Id) (*GeneralLedger, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Posting not implemented")
}
func (UnimplementedGeneralJournalServiceServer) mustEmbedUnimplementedGeneralJournalServiceServer() {}

// UnsafeGeneralJournalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneralJournalServiceServer will
// result in compilation errors.
type UnsafeGeneralJournalServiceServer interface {
	mustEmbedUnimplementedGeneralJournalServiceServer()
}

func RegisterGeneralJournalServiceServer(s grpc.ServiceRegistrar, srv GeneralJournalServiceServer) {
	s.RegisterService(&GeneralJournalService_ServiceDesc, srv)
}

func _GeneralJournalService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeneralJournalServiceServer).List(m, &generalJournalServiceListServer{stream})
}

type GeneralJournalService_ListServer interface {
	Send(*GeneralJournal) error
	grpc.ServerStream
}

type generalJournalServiceListServer struct {
	grpc.ServerStream
}

func (x *generalJournalServiceListServer) Send(m *GeneralJournal) error {
	return x.ServerStream.SendMsg(m)
}

func _GeneralJournalService_Posting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneralJournalServiceServer).Posting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.GeneralJournalService/Posting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneralJournalServiceServer).Posting(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// GeneralJournalService_ServiceDesc is the grpc.ServiceDesc for GeneralJournalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeneralJournalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wiradata.ledgers.GeneralJournalService",
	HandlerType: (*GeneralJournalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Posting",
			Handler:    _GeneralJournalService_Posting_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _GeneralJournalService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ledgers/general_journal_service.proto",
}
