// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: ledgers/report_service.proto

package ledgers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportServiceClient interface {
	GetIncomeStatement(ctx context.Context, in *ReportPeriod, opts ...grpc.CallOption) (*IncomeStatement, error)
	GetBalanceSheet(ctx context.Context, in *ReportPeriod, opts ...grpc.CallOption) (*BalanceSheet, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) GetIncomeStatement(ctx context.Context, in *ReportPeriod, opts ...grpc.CallOption) (*IncomeStatement, error) {
	out := new(IncomeStatement)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.ReportService/GetIncomeStatement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetBalanceSheet(ctx context.Context, in *ReportPeriod, opts ...grpc.CallOption) (*BalanceSheet, error) {
	out := new(BalanceSheet)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.ReportService/GetBalanceSheet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations must embed UnimplementedReportServiceServer
// for forward compatibility
type ReportServiceServer interface {
	GetIncomeStatement(context.Context, *ReportPeriod) (*IncomeStatement, error)
	GetBalanceSheet(context.Context, *ReportPeriod) (*BalanceSheet, error)
	mustEmbedUnimplementedReportServiceServer()
}

// UnimplementedReportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (UnimplementedReportServiceServer) GetIncomeStatement(context.Context, *ReportPeriod) (*IncomeStatement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncomeStatement not implemented")
}
func (UnimplementedReportServiceServer) GetBalanceSheet(context.Context, *ReportPeriod) (*BalanceSheet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalanceSheet not implemented")
}
func (UnimplementedReportServiceServer) mustEmbedUnimplementedReportServiceServer() {}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_GetIncomeStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPeriod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetIncomeStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.ReportService/GetIncomeStatement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetIncomeStatement(ctx, req.(*ReportPeriod))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetBalanceSheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPeriod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetBalanceSheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.ReportService/GetBalanceSheet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetBalanceSheet(ctx, req.(*ReportPeriod))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wiradata.ledgers.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIncomeStatement",
			Handler:    _ReportService_GetIncomeStatement_Handler,
		},
		{
			MethodName: "GetBalanceSheet",
			Handler:    _ReportService_GetBalanceSheet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledgers/report_service.proto",
}
