// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.13.0
// source: ledgers/report_message.proto

package ledgers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncomeStatement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Period       string         `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"` // Contoh: "Bulan Januari 2023"
	IncomeItems  []*AccountItem `protobuf:"bytes,2,rep,name=income_items,json=incomeItems,proto3" json:"income_items,omitempty"`
	ExpenseItems []*AccountItem `protobuf:"bytes,3,rep,name=expense_items,json=expenseItems,proto3" json:"expense_items,omitempty"`
	NetProfit    float64        `protobuf:"fixed64,4,opt,name=net_profit,json=netProfit,proto3" json:"net_profit,omitempty"`
}

func (x *IncomeStatement) Reset() {
	*x = IncomeStatement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ledgers_report_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncomeStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeStatement) ProtoMessage() {}

func (x *IncomeStatement) ProtoReflect() protoreflect.Message {
	mi := &file_ledgers_report_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeStatement.ProtoReflect.Descriptor instead.
func (*IncomeStatement) Descriptor() ([]byte, []int) {
	return file_ledgers_report_message_proto_rawDescGZIP(), []int{0}
}

func (x *IncomeStatement) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *IncomeStatement) GetIncomeItems() []*AccountItem {
	if x != nil {
		return x.IncomeItems
	}
	return nil
}

func (x *IncomeStatement) GetExpenseItems() []*AccountItem {
	if x != nil {
		return x.ExpenseItems
	}
	return nil
}

func (x *IncomeStatement) GetNetProfit() float64 {
	if x != nil {
		return x.NetProfit
	}
	return 0
}

type BalanceSheet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date        string         `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // Contoh: "31 Desember 2023"
	Assets      []*AccountItem `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	Liabilities []*AccountItem `protobuf:"bytes,3,rep,name=liabilities,proto3" json:"liabilities,omitempty"`
	Equity      float64        `protobuf:"fixed64,4,opt,name=equity,proto3" json:"equity,omitempty"`
}

func (x *BalanceSheet) Reset() {
	*x = BalanceSheet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ledgers_report_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceSheet) ProtoMessage() {}

func (x *BalanceSheet) ProtoReflect() protoreflect.Message {
	mi := &file_ledgers_report_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceSheet.ProtoReflect.Descriptor instead.
func (*BalanceSheet) Descriptor() ([]byte, []int) {
	return file_ledgers_report_message_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceSheet) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *BalanceSheet) GetAssets() []*AccountItem {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *BalanceSheet) GetLiabilities() []*AccountItem {
	if x != nil {
		return x.Liabilities
	}
	return nil
}

func (x *BalanceSheet) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

type AccountItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *AccountItem) Reset() {
	*x = AccountItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ledgers_report_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountItem) ProtoMessage() {}

func (x *AccountItem) ProtoReflect() protoreflect.Message {
	mi := &file_ledgers_report_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountItem.ProtoReflect.Descriptor instead.
func (*AccountItem) Descriptor() ([]byte, []int) {
	return file_ledgers_report_message_proto_rawDescGZIP(), []int{2}
}

func (x *AccountItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReportPeriod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Period string `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
}

func (x *ReportPeriod) Reset() {
	*x = ReportPeriod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ledgers_report_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPeriod) ProtoMessage() {}

func (x *ReportPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_ledgers_report_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPeriod.ProtoReflect.Descriptor instead.
func (*ReportPeriod) Descriptor() ([]byte, []int) {
	return file_ledgers_report_message_proto_rawDescGZIP(), []int{3}
}

func (x *ReportPeriod) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

var File_ledgers_report_message_proto protoreflect.FileDescriptor

var file_ledgers_report_message_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73,
	0x22, 0xce, 0x01, 0x0a, 0x0f, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x40, 0x0a, 0x0c,
	0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x0b, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x42,
	0x0a, 0x0d, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x74, 0x22, 0xb2, 0x01, 0x0a, 0x0c, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x68, 0x65,
	0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x3f, 0x0a,
	0x0b, 0x6c, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x0b, 0x6c, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x71, 0x75, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x65, 0x71, 0x75, 0x69, 0x74, 0x79, 0x22, 0x39, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x26, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x42, 0x3b, 0x0a, 0x23, 0x63, 0x6f, 0x6d,
	0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x65, 0x72, 0x70, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73,
	0x50, 0x01, 0x5a, 0x12, 0x70, 0x62, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x3b, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ledgers_report_message_proto_rawDescOnce sync.Once
	file_ledgers_report_message_proto_rawDescData = file_ledgers_report_message_proto_rawDesc
)

func file_ledgers_report_message_proto_rawDescGZIP() []byte {
	file_ledgers_report_message_proto_rawDescOnce.Do(func() {
		file_ledgers_report_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_ledgers_report_message_proto_rawDescData)
	})
	return file_ledgers_report_message_proto_rawDescData
}

var file_ledgers_report_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ledgers_report_message_proto_goTypes = []interface{}{
	(*IncomeStatement)(nil), // 0: wiradata.ledgers.IncomeStatement
	(*BalanceSheet)(nil),    // 1: wiradata.ledgers.BalanceSheet
	(*AccountItem)(nil),     // 2: wiradata.ledgers.AccountItem
	(*ReportPeriod)(nil),    // 3: wiradata.ledgers.ReportPeriod
}
var file_ledgers_report_message_proto_depIdxs = []int32{
	2, // 0: wiradata.ledgers.IncomeStatement.income_items:type_name -> wiradata.ledgers.AccountItem
	2, // 1: wiradata.ledgers.IncomeStatement.expense_items:type_name -> wiradata.ledgers.AccountItem
	2, // 2: wiradata.ledgers.BalanceSheet.assets:type_name -> wiradata.ledgers.AccountItem
	2, // 3: wiradata.ledgers.BalanceSheet.liabilities:type_name -> wiradata.ledgers.AccountItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ledgers_report_message_proto_init() }
func file_ledgers_report_message_proto_init() {
	if File_ledgers_report_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ledgers_report_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncomeStatement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ledgers_report_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceSheet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ledgers_report_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ledgers_report_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportPeriod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ledgers_report_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ledgers_report_message_proto_goTypes,
		DependencyIndexes: file_ledgers_report_message_proto_depIdxs,
		MessageInfos:      file_ledgers_report_message_proto_msgTypes,
	}.Build()
	File_ledgers_report_message_proto = out.File
	file_ledgers_report_message_proto_rawDesc = nil
	file_ledgers_report_message_proto_goTypes = nil
	file_ledgers_report_message_proto_depIdxs = nil
}
