// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: ledgers/return_sales_service.proto

package ledgers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReturnSalesServiceClient is the client API for ReturnSalesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReturnSalesServiceClient interface {
	Create(ctx context.Context, in *ReturnSales, opts ...grpc.CallOption) (*ReturnSales, error)
	Update(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ReturnSales, error)
}

type returnSalesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReturnSalesServiceClient(cc grpc.ClientConnInterface) ReturnSalesServiceClient {
	return &returnSalesServiceClient{cc}
}

func (c *returnSalesServiceClient) Create(ctx context.Context, in *ReturnSales, opts ...grpc.CallOption) (*ReturnSales, error) {
	out := new(ReturnSales)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.ReturnSalesService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *returnSalesServiceClient) Update(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ReturnSales, error) {
	out := new(ReturnSales)
	err := c.cc.Invoke(ctx, "/wiradata.ledgers.ReturnSalesService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReturnSalesServiceServer is the server API for ReturnSalesService service.
// All implementations must embed UnimplementedReturnSalesServiceServer
// for forward compatibility
type ReturnSalesServiceServer interface {
	Create(context.Context, *ReturnSales) (*ReturnSales, error)
	Update(context.Context, *Id) (*ReturnSales, error)
	mustEmbedUnimplementedReturnSalesServiceServer()
}

// UnimplementedReturnSalesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReturnSalesServiceServer struct {
}

func (UnimplementedReturnSalesServiceServer) Create(context.Context, *ReturnSales) (*ReturnSales, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedReturnSalesServiceServer) Update(context.Context, *Id) (*ReturnSales, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedReturnSalesServiceServer) mustEmbedUnimplementedReturnSalesServiceServer() {}

// UnsafeReturnSalesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReturnSalesServiceServer will
// result in compilation errors.
type UnsafeReturnSalesServiceServer interface {
	mustEmbedUnimplementedReturnSalesServiceServer()
}

func RegisterReturnSalesServiceServer(s grpc.ServiceRegistrar, srv ReturnSalesServiceServer) {
	s.RegisterService(&ReturnSalesService_ServiceDesc, srv)
}

func _ReturnSalesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnSales)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReturnSalesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.ReturnSalesService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReturnSalesServiceServer).Create(ctx, req.(*ReturnSales))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReturnSalesService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReturnSalesServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.ledgers.ReturnSalesService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReturnSalesServiceServer).Update(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// ReturnSalesService_ServiceDesc is the grpc.ServiceDesc for ReturnSalesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReturnSalesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wiradata.ledgers.ReturnSalesService",
	HandlerType: (*ReturnSalesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ReturnSalesService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ReturnSalesService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledgers/return_sales_service.proto",
}
